# Site Settings
lang: en
title: Luis Pastrana
tagline: Luis Pastrana's blog
email: pastrana.garcia@outlook.com
description: >
  Luis Pastrana's blog
baseurl: ""
url: "" # url: "https://pxstrana.github.io/"
permalink: pretty
remote_theme: pxstrana/portfolio
#favicon: /path/to/favicon.png
#gh_sponsor: 
#hide_share_buttons: true
#theme_color: '#eeeeee'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 8
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Luis Pastrana"
      layout: post
      show_sidebar: false

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu
